version: '3.8'
services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - mypostgres:/var/mypostgres
    environment:
      - POSTGRES_PASSWORD=password
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - 7000:8978
    depends_on:
      - postgresql
  apicurio:
    image: apicurio/apicurio-registry-sql:latest-snapshot
    ports: 
      - 9000:8080
    depends_on:
      - postgresql
    environment:
      - REGISTRY_DATASOURCE_URL=${PGURL}
      - REGISTRY_DATASOURCE_USERNAME=${PGUSER}
      - REGISTRY_DATASOURCE_PASSWORD=${PGPASSWORD}
volumes:
  mypostgres: